baseURL = 'https://mfreimueller.com/'
languageCode = 'en-us'
title = 'Michael Freimüller'
Copyright = 'Copyright 2023 Michael Freimüller Released under Creative Commons Zero v1.0 Universal license'
theme = 'arete'

[Params]
author = 'Michael Freimüller'
ShowThemeInfo = true
mainSections = ['blog','essays']

[mediaTypes]
[mediaTypes.'application/rss+xml']
suffixes = ['xml']